* HPGE: Haptic Plugin for Game Engines

This is the C/C++ library, based on CHAI3D, which can be used together with the
[[https://github.com/HapticPlugin/HPGE-wrappers][HPGE-wrappers]] to use haptic devices in Unity3D.

* Compile Instructions

** Linux

If you are on a Guix System, or on a debian derivate, you can use guix to build
the library

#+begin_src bash
# On debian-based only
sudo apt install guix
guix pull
# After
guix build -f guix.scm
#+end_src

Or you can install the dependencies and run
#+begin_src bash
meson build
ninja -C build
#+end_src

Dependencies are specified in the [[file:guix.scm][guix.scm]] file and should be:
- libusb
- eigen
- meson
- ninja
- pkg-config
- gcc
- ncurses5 (required for the phantom device only)

** Windows

You can run the script [[file:fetch_dependencies_win.sh][fetch_dependencies_win.sh]] under [[https://git-scm.com/downloads][git bash]].  It
requires a working Visual Studio installation.  If you have experience with
windows, please help me out fixing this paragraph!

You basically need to install:
- python
- ninja
- meson
- Visual Studio

Then you *have to* reboot.

Open a ~Windows Native Prompt~
(e.g., =C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2019\Visual Studio Tools\VC\x64 Native Tools Command Prompt for VS 2019.lnk=)
and run the following commands:

#+begin_src bash
meson.py --buildtype release --backend ninja buildVSNinjaRel
ninja -C buildVSNinjaRel
#+end_src

(depending on how you installed meson, teh command might be =meson.py= or =meson=)

Or if you want to hack it in visual studio:
#+begin_src bash
meson.py --buildtype release --backend vs2019 buildVSRel
#+end_src


* Reference
For scientific publications, please reference HPGE:

#+begin_src bibtex
@inproceedings{balzarotti2019hpge,
  title={Hpge: an haptic plugin for game engines},
  author={Balzarotti, Nicol{\`o} and Baud-Bovy, Gabriel},
  booktitle={Games and Learning Alliance: 7th International Conference, GALA 2018, Palermo, Italy, December 5--7, 2018, Proceedings 7},
  pages={330--339},
  year={2019},
  organization={Springer}
}
#+end_src

(C) 2017-2023 by Istituto Italiano di Tecnologia
All Rights Reserved.

HPGE contributors:
- Nicolò Balzarotti
- Gabriel Baud-Bovy
